package com.moon.dao;

import com.moon.entity.China;
import java.util.List;

public interface ChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int insert(China record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    China selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    List<China> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int updateByPrimaryKey(China record);
}