package com.moon.dao;

import com.moon.entity.Forder;
import java.util.List;

public interface ForderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int insert(Forder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    Forder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    List<Forder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int updateByPrimaryKey(Forder record);
}