package com.moon.dao;

import com.moon.entity.Fuser;
import java.util.List;

public interface FuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuser
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuser
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int insert(Fuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuser
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    Fuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuser
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    List<Fuser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuser
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int updateByPrimaryKey(Fuser record);
}