package com.moon.dao;

import com.moon.entity.Orderdetail;
import java.util.List;

public interface OrderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int insert(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    Orderdetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    List<Orderdetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int updateByPrimaryKey(Orderdetail record);
}