package com.moon.dao;

import com.moon.entity.Ptype;
import java.util.List;

public interface PtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptype
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptype
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int insert(Ptype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptype
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    Ptype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptype
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    List<Ptype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptype
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    int updateByPrimaryKey(Ptype record);
}