package com.moon.entity;

import java.io.Serializable;
import java.util.Date;

public class Addressbook implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressbook.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressbook.userId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressbook.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressbook.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressbook.fulladdr
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String fulladdr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table addressbook
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressbook.id
     *
     * @return the value of addressbook.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressbook.id
     *
     * @param id the value for addressbook.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressbook.userId
     *
     * @return the value of addressbook.userId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressbook.userId
     *
     * @param userid the value for addressbook.userId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressbook.createtime
     *
     * @return the value of addressbook.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressbook.createtime
     *
     * @param createtime the value for addressbook.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressbook.state
     *
     * @return the value of addressbook.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressbook.state
     *
     * @param state the value for addressbook.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressbook.fulladdr
     *
     * @return the value of addressbook.fulladdr
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getFulladdr() {
        return fulladdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressbook.fulladdr
     *
     * @param fulladdr the value for addressbook.fulladdr
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setFulladdr(String fulladdr) {
        this.fulladdr = fulladdr;
    }
}