package com.moon.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Cartitem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.foodId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer foodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.foodName
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String foodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.price
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.fcount
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer fcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.sumPrice
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private BigDecimal sumprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.userId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartitem.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cartitem
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.id
     *
     * @return the value of cartitem.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.id
     *
     * @param id the value for cartitem.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.foodId
     *
     * @return the value of cartitem.foodId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getFoodid() {
        return foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.foodId
     *
     * @param foodid the value for cartitem.foodId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setFoodid(Integer foodid) {
        this.foodid = foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.foodName
     *
     * @return the value of cartitem.foodName
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.foodName
     *
     * @param foodname the value for cartitem.foodName
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.price
     *
     * @return the value of cartitem.price
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.price
     *
     * @param price the value for cartitem.price
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.fcount
     *
     * @return the value of cartitem.fcount
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getFcount() {
        return fcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.fcount
     *
     * @param fcount the value for cartitem.fcount
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setFcount(Integer fcount) {
        this.fcount = fcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.sumPrice
     *
     * @return the value of cartitem.sumPrice
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public BigDecimal getSumprice() {
        return sumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.sumPrice
     *
     * @param sumprice the value for cartitem.sumPrice
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setSumprice(BigDecimal sumprice) {
        this.sumprice = sumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.userId
     *
     * @return the value of cartitem.userId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.userId
     *
     * @param userid the value for cartitem.userId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.createtime
     *
     * @return the value of cartitem.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.createtime
     *
     * @param createtime the value for cartitem.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartitem.state
     *
     * @return the value of cartitem.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartitem.state
     *
     * @param state the value for cartitem.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }
}