package com.moon.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Forder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.totalprice
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private BigDecimal totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.userId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.prov
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String prov;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.city
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.district
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.district2
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String district2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.addr
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table forder
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.id
     *
     * @return the value of forder.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.id
     *
     * @param id the value for forder.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.totalprice
     *
     * @return the value of forder.totalprice
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.totalprice
     *
     * @param totalprice the value for forder.totalprice
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.userId
     *
     * @return the value of forder.userId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.userId
     *
     * @param userid the value for forder.userId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.prov
     *
     * @return the value of forder.prov
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getProv() {
        return prov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.prov
     *
     * @param prov the value for forder.prov
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setProv(String prov) {
        this.prov = prov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.city
     *
     * @return the value of forder.city
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.city
     *
     * @param city the value for forder.city
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.district
     *
     * @return the value of forder.district
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.district
     *
     * @param district the value for forder.district
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.district2
     *
     * @return the value of forder.district2
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getDistrict2() {
        return district2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.district2
     *
     * @param district2 the value for forder.district2
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setDistrict2(String district2) {
        this.district2 = district2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.createtime
     *
     * @return the value of forder.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.createtime
     *
     * @param createtime the value for forder.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.state
     *
     * @return the value of forder.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.state
     *
     * @param state the value for forder.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.addr
     *
     * @return the value of forder.addr
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.addr
     *
     * @param addr the value for forder.addr
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }
}