package com.moon.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Orderdetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.foodId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer foodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.foodName
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String foodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.price
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.fcount
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer fcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.sumprice
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private BigDecimal sumprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.orderId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.id
     *
     * @return the value of orderdetail.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.id
     *
     * @param id the value for orderdetail.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.foodId
     *
     * @return the value of orderdetail.foodId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getFoodid() {
        return foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.foodId
     *
     * @param foodid the value for orderdetail.foodId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setFoodid(Integer foodid) {
        this.foodid = foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.foodName
     *
     * @return the value of orderdetail.foodName
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.foodName
     *
     * @param foodname the value for orderdetail.foodName
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.price
     *
     * @return the value of orderdetail.price
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.price
     *
     * @param price the value for orderdetail.price
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.fcount
     *
     * @return the value of orderdetail.fcount
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getFcount() {
        return fcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.fcount
     *
     * @param fcount the value for orderdetail.fcount
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setFcount(Integer fcount) {
        this.fcount = fcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.sumprice
     *
     * @return the value of orderdetail.sumprice
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public BigDecimal getSumprice() {
        return sumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.sumprice
     *
     * @param sumprice the value for orderdetail.sumprice
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setSumprice(BigDecimal sumprice) {
        this.sumprice = sumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.orderId
     *
     * @return the value of orderdetail.orderId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.orderId
     *
     * @param orderid the value for orderdetail.orderId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.createtime
     *
     * @return the value of orderdetail.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.createtime
     *
     * @param createtime the value for orderdetail.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.state
     *
     * @return the value of orderdetail.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.state
     *
     * @param state the value for orderdetail.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }
}