package com.moon.entity;

import java.io.Serializable;
import java.util.Date;

public class Provider implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.name
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.typeId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.consume
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer consume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.location
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.detail
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.imgsrc
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private String imgsrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table provider
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.id
     *
     * @return the value of provider.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.id
     *
     * @param id the value for provider.id
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.name
     *
     * @return the value of provider.name
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.name
     *
     * @param name the value for provider.name
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.typeId
     *
     * @return the value of provider.typeId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.typeId
     *
     * @param typeid the value for provider.typeId
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.consume
     *
     * @return the value of provider.consume
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getConsume() {
        return consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.consume
     *
     * @param consume the value for provider.consume
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setConsume(Integer consume) {
        this.consume = consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.location
     *
     * @return the value of provider.location
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.location
     *
     * @param location the value for provider.location
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.createtime
     *
     * @return the value of provider.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.createtime
     *
     * @param createtime the value for provider.createtime
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.state
     *
     * @return the value of provider.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.state
     *
     * @param state the value for provider.state
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.detail
     *
     * @return the value of provider.detail
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.detail
     *
     * @param detail the value for provider.detail
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.imgsrc
     *
     * @return the value of provider.imgsrc
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public String getImgsrc() {
        return imgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.imgsrc
     *
     * @param imgsrc the value for provider.imgsrc
     *
     * @mbg.generated Mon Sep 26 16:01:30 CST 2022
     */
    public void setImgsrc(String imgsrc) {
        this.imgsrc = imgsrc;
    }
}